authentication:
  jwt:
    secret:
      My Secret
host:
  port: 5000
  ssl:
    cert: /home/bassie/Work/ssl-cert/mintserver1/mintserver1.crt
    key: /home/bassie/Work/ssl-cert/mintserver1/mintserver1.key